In [1]:
import pandas as pd

In [2]:
orders=pd.read_csv(r"C:\Users\H S COMPUTER S HYD\Desktop\orders.csv")

In [3]:
products=pd.read_csv(r"C:\Users\H S COMPUTER S HYD\Desktop\products.csv")

In [4]:
customers=pd.read_csv(r"C:\Users\H S COMPUTER S HYD\Desktop\customers.csv")

In [5]:
merged_order=orders.merge(products,on="product_id",how="left")

In [6]:
merged_order["total_price"]=merged_order.quantity*merged_order.price
merged_order

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,total_price
0,O00001,C0333,P022,1,1/9/2022,Tax,Home,185.33,185.33
1,O00002,C0068,P090,1,1/27/2022,Perform,Electronics,947.55,947.55
2,O00003,C0483,P021,1,1/17/2022,Art,Electronics,938.65,938.65
3,O00004,C0214,P076,4,1/7/2022,Amount,Electronics,154.17,616.68
4,O00005,C0411,P073,4,1/12/2022,Second,Electronics,131.85,527.40
...,...,...,...,...,...,...,...,...,...
2579,O02580,C0237,P098,5,12/22/2024,Decision,Accessories,567.31,2836.55
2580,O02581,C0236,P007,1,12/5/2024,Finish,Clothing,325.74,325.74
2581,O02582,C0029,P035,1,12/12/2024,First,Clothing,362.04,362.04
2582,O02583,C0171,P077,1,12/16/2024,Government,Clothing,233.11,233.11
2583,O02584,C0421,P038,5,12/1/2024,Black,Electronics,817.52,4087.60

In [7]:
customer_repeat=merged_order.customer_id.value_counts()

In [8]:
customer_repeat

customer_id
C0028    13
C0113    13
C0243    12
C0338    11
C0475    11
         ..
C0279     1
C0152     1
C0260     1
C0227     1
C0263     1
Name: count, Length: 498, dtype: int64

In [9]:
order_repeat=merged_order.product_id.value_counts()
order_repeat

product_id
P041    39
P059    38
P022    36
P056    36
P099    33
        ..
P010    18
P061    18
P033    18
P068    16
P035    14
Name: count, Length: 100, dtype: int64

In [10]:
merged_order[merged_order["product_id"]==order_repeat.index[0]]

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,total_price
11,O00012,C0336,P041,1,1/16/2022,Behind,Footwear,465.37,465.37
30,O00031,C0229,P041,1,1/31/2022,Behind,Footwear,465.37,465.37
75,O00076,C0441,P041,5,1/15/2022,Behind,Footwear,465.37,2326.85
293,O00294,C0410,P041,4,4/27/2022,Behind,Footwear,465.37,1861.48
299,O00300,C0244,P041,3,4/7/2022,Behind,Footwear,465.37,1396.11
321,O00322,C0236,P041,1,4/1/2022,Behind,Footwear,465.37,465.37
350,O00351,C0161,P041,3,5/12/2022,Behind,Footwear,465.37,1396.11
467,O00468,C0463,P041,5,7/20/2022,Behind,Footwear,465.37,2326.85
480,O00481,C0439,P041,1,7/7/2022,Behind,Footwear,465.37,465.37
503,O00504,C0022,P041,5,7/20/2022,Behind,Footwear,465.37,2326.85
568,O00569,C0095,P041,2,8/25/2022,Behind,Footwear,465.37,930.74
577,O00578,C0369,P041,4,9/20/2022,Behind,Footwear,465.37,1861.48
673,O00674,C0362,P041,1,10/27/2022,Behind,Footwear,465.37,465.37
738,O00739,C0349,P041,3,11/17/2022,Behind,Footwear,465.37,1396.11
805,O00806,C0348,P041,5,12/3/2022,Behind,Footwear,465.37,2326.85
982,O00983,C0022,P041,5,3/28/2023,Behind,Footwear,465.37,2326.85
986,O00987,C0341,P041,3,3/25/2023,Behind,Footwear,465.37,1396.11
1117,O01118,C0231,P041,4,5/13/2023,Behind,Footwear,465.37,1861.48
1226,O01227,C0406,P041,4,6/4/2023,Behind,Footwear,465.37,1861.48
1281,O01282,C0265,P041,4,6/30/2023,Behind,Footwear,465.37,1861.48
1903,O01904,C0437,P041,4,3/29/2024,Behind,Footwear,465.37,1861.48
1907,O01908,C0217,P041,3,3/8/2024,Behind,Footwear,465.37,1396.11
1917,O01918,C0307,P041,3,3/5/2024,Behind,Footwear,465.37,1396.11
1961,O01962,C0410,P041,1,4/4/2024,Behind,Footwear,465.37,465.37
1973,O01974,C0356,P041,5,4/19/2024,Behind,Footwear,465.37,2326.85
2030,O02031,C0395,P041,1,4/20/2024,Behind,Footwear,465.37,465.37
2200,O02201,C0181,P041,4,7/5/2024,Behind,Footwear,465.37,1861.48
2236,O02237,C0245,P041,4,8/4/2024,Behind,Footwear,465.37,1861.48
2251,O02252,C0025,P041,1,8/3/2024,Behind,Footwear,465.37,465.37
2255,O02256,C0100,P041,4,8/27/2024,Behind,Footwear,465.37,1861.48
2288,O02289,C0034,P041,3,9/4/2024,Behind,Footwear,465.37,1396.11
2321,O02322,C0443,P041,1,9/16/2024,Behind,Footwear,465.37,465.37
2353,O02354,C0463,P041,5,10/17/2024,Behind,Footwear,465.37,2326.85
2383,O02384,C0193,P041,4,10/26/2024,Behind,Footwear,465.37,1861.48
2413,O02414,C0418,P041,5,10/26/2024,Behind,Footwear,465.37,2326.85
2449,O02450,C0065,P041,2,11/11/2024,Behind,Footwear,465.37,930.74
2466,O02467,C0264,P041,3,11/11/2024,Behind,Footwear,465.37,1396.11
2510,O02511,C0088,P041,1,11/11/2024,Behind,Footwear,465.37,465.37
2566,O02567,C0356,P041,5,12/20/2024,Behind,Footwear,465.37,2326.85

In [11]:
min_order=merged_order.product_id.value_counts().index[-1]
min_order

'P035'

In [12]:
merged_order[merged_order["product_id"]==min_order]

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,total_price
351,O00352,C0364,P035,5,5/28/2022,First,Clothing,362.04,1810.20
377,O00378,C0415,P035,4,6/15/2022,First,Clothing,362.04,1448.16
381,O00382,C0232,P035,5,6/6/2022,First,Clothing,362.04,1810.20
393,O00394,C0029,P035,4,6/21/2022,First,Clothing,362.04,1448.16
810,O00811,C0172,P035,3,12/8/2022,First,Clothing,362.04,1086.12
1246,O01247,C0098,P035,3,6/19/2023,First,Clothing,362.04,1086.12
1404,O01405,C0044,P035,3,8/27/2023,First,Clothing,362.04,1086.12
1659,O01660,C0243,P035,5,11/20/2023,First,Clothing,362.04,1810.20
1997,O01998,C0040,P035,1,4/26/2024,First,Clothing,362.04,362.04
2019,O02020,C0377,P035,1,4/26/2024,First,Clothing,362.04,362.04
2061,O02062,C0416,P035,1,5/13/2024,First,Clothing,362.04,362.04
2169,O02170,C0355,P035,5,7/12/2024,First,Clothing,362.04,1810.20
2239,O02240,C0100,P035,1,8/3/2024,First,Clothing,362.04,362.04
2581,O02582,C0029,P035,1,12/12/2024,First,Clothing,362.04,362.04

In [13]:
def discount(dis):
    if dis>5 or dis==5:
        return(dis)

In [14]:
merged_order["discount"]=merged_order.customer_id.value_counts().apply(discount).dropna()
merged_order

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,total_price,discount
0,O00001,C0333,P022,1,1/9/2022,Tax,Home,185.33,185.33,NaN
1,O00002,C0068,P090,1,1/27/2022,Perform,Electronics,947.55,947.55,NaN
2,O00003,C0483,P021,1,1/17/2022,Art,Electronics,938.65,938.65,NaN
3,O00004,C0214,P076,4,1/7/2022,Amount,Electronics,154.17,616.68,NaN
4,O00005,C0411,P073,4,1/12/2022,Second,Electronics,131.85,527.40,NaN
...,...,...,...,...,...,...,...,...,...,...
2579,O02580,C0237,P098,5,12/22/2024,Decision,Accessories,567.31,2836.55,NaN
2580,O02581,C0236,P007,1,12/5/2024,Finish,Clothing,325.74,325.74,NaN
2581,O02582,C0029,P035,1,12/12/2024,First,Clothing,362.04,362.04,NaN
2582,O02583,C0171,P077,1,12/16/2024,Government,Clothing,233.11,233.11,NaN
2583,O02584,C0421,P038,5,12/1/2024,Black,Electronics,817.52,4087.60,NaN

In [15]:
revanue=merged_order["total_price"].sum()
revanue

np.float64(4134260.59)

In [16]:
merged_order["Year"]=merged_order["order_date"].str.split("/").str[2].astype(int)

In [17]:
merged_order["Month"]=merged_order["order_date"].str.split("/").str[0].astype(int)

In [18]:
merged_order

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,total_price,discount,Year,Month
0,O00001,C0333,P022,1,1/9/2022,Tax,Home,185.33,185.33,NaN,2022,1
1,O00002,C0068,P090,1,1/27/2022,Perform,Electronics,947.55,947.55,NaN,2022,1
2,O00003,C0483,P021,1,1/17/2022,Art,Electronics,938.65,938.65,NaN,2022,1
3,O00004,C0214,P076,4,1/7/2022,Amount,Electronics,154.17,616.68,NaN,2022,1
4,O00005,C0411,P073,4,1/12/2022,Second,Electronics,131.85,527.40,NaN,2022,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2579,O02580,C0237,P098,5,12/22/2024,Decision,Accessories,567.31,2836.55,NaN,2024,12
2580,O02581,C0236,P007,1,12/5/2024,Finish,Clothing,325.74,325.74,NaN,2024,12
2581,O02582,C0029,P035,1,12/12/2024,First,Clothing,362.04,362.04,NaN,2024,12
2582,O02583,C0171,P077,1,12/16/2024,Government,Clothing,233.11,233.11,NaN,2024,12
2583,O02584,C0421,P038,5,12/1/2024,Black,Electronics,817.52,4087.60,NaN,2024,12

In [19]:
group=merged_order.groupby("Year")

In [20]:
Mo=merged_order.Month.unique()
Mo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
Ye=merged_order.Year.unique()
Ye

array([2022, 2023, 2024])

In [24]:
for ye in Ye:
    print(ye)
    g=merged_order.groupby("Year")
    ye_g=g.get_group(ye)
    Repeat=ye_g.customer_id.value_counts()
    Top=ye_g.product_name.value_counts()
    least=ye_g.product_name.value_counts().index[-1]
    Revanue=ye_g["total_price"].sum()
    print(f"--Repeated_order--\n{Repeat}\n--Top_selling_Sold--\n{Top}\n--Least_Sold--\n{least}\n--Revanue--\n{Revanue}")

2022
--Repeated_order--
customer_id
C0267    6
C0080    6
C0129    6
C0028    6
C0364    5
        ..
C0017    1
C0226    1
C0279    1
C0137    1
C0363    1
Name: count, Length: 417, dtype: int64
--Top_selling_Sold--
product_name
Program     17
Network     17
Behind      15
Perform     15
So          15
            ..
News         4
Decision     4
Seem         3
Follow       3
Protect      3
Name: count, Length: 95, dtype: int64
--Least_Sold--
Protect
--Revanue--
1357500.38
2023
--Repeated_order--
customer_id
C0414    7
C0068    6
C0391    6
C0243    6
C0354    6
        ..
C0203    1
C0298    1
C0441    1
C0361    1
C0020    1
Name: count, Length: 428, dtype: int64
--Top_selling_Sold--
product_name
North       23
Table       20
Some        19
Program     17
Stage       15
            ..
Strategy     4
Possible     4
Country      4
Standard     3
First        3
Name: count, Length: 95, dtype: int64
--Least_Sold--
First
--Revanue--
1489071.01
2024
--Repeated_order--
customer_id
C0220    9
C0475    6
C0310    6
C0461    5
C0149    5
        ..
C0060    1
C0324    1
C0210    1
C0375    1
C0029    1
Name: count, Length: 404, dtype: int64
--Top_selling_Sold--
product_name
Table        21
Behind       19
North        19
Program      16
Stage        14
             ..
Dream         4
Operation     4
On            3
The           3
Ask           2
Name: count, Length: 95, dtype: int64
--Least_Sold--
Ask
--Revanue--
1287689.2000000002

In [25]:
for y in Ye:
    gy=merged_order.groupby("Year")
    g_ye=g.get_group(y)
    print(y)
    for mo in Mo:
        gm=g_ye.groupby("Month")
        GM=gm.get_group(mo)
        print(mo)
        Repeat=GM.customer_id.value_counts()
        Top=GM.product_name.value_counts()
        least=GM.product_name.value_counts().index[-1]
        revanue=GM["total_price"].sum()
        print(f"--Repeated--\n{Repeat}\n--Top_Product--\n{Top}\n--Least_Product--\n{least}\n--Revanue--\n{revanue}")

2022
1
--Repeated--
customer_id
C0147    2
C0490    2
C0235    2
C0053    2
C0248    2
        ..
C0229    1
C0230    1
C0236    1
C0207    1
C0402    1
Name: count, Length: 90, dtype: int64
--Top_Product--
product_name
Table      4
Tax        3
Behind     3
Away       3
Perform    3
          ..
List       1
On         1
Least      1
Ready      1
Believe    1
Name: count, Length: 61, dtype: int64
--Least_Product--
Believe
--Revanue--
174606.83000000002
2
--Repeated--
customer_id
C0184    2
C0013    2
C0491    2
C0276    2
C0113    1
        ..
C0028    1
C0286    1
C0421    1
C0209    1
C0316    1
Name: count, Length: 70, dtype: int64
--Top_Product--
product_name
Away             4
Able             3
Edge             3
Keep             3
Strategy         2
Ready            2
Believe          2
Section          2
Perform          2
Trip             2
Drive            2
Really           2
Country          2
Such             2
Art              2
Stage            2
Black            2
Force            2
List             2
Phone            1
Maybe            1
General          1
West             1
Body             1
Least            1
Second           1
Store            1
Dream            1
Same             1
Ahead            1
Be               1
Some             1
Government       1
Seem             1
On               1
Environmental    1
Mind             1
Number           1
Operation        1
Ask              1
Network          1
Yes              1
So               1
Pay              1
Possible         1
Organization     1
Eat              1
Follow           1
Manage           1
Job              1
Name: count, dtype: int64
--Least_Product--
Job
--Revanue--
131429.46
3
--Repeated--
customer_id
C0083    3
C0092    2
C0268    2
C0424    2
C0113    2
        ..
C0368    1
C0081    1
C0109    1
C0040    1
C0315    1
Name: count, Length: 84, dtype: int64
--Top_Product--
product_name
Tax              4
Program          4
Ahead            4
Environmental    3
Ask              3
Standard         3
Add              3
Second           3
Light            2
Amount           2
Really           2
Where            2
Senior           2
Manage           2
Stage            2
Maybe            2
According        2
Mind             2
Operation        2
News             2
Around           2
Network          2
Country          2
Perform          2
Foot             2
Phone            1
Seem             1
Dream            1
Work             1
Prepare          1
Follow           1
Many             1
Keep             1
So               1
General          1
Consumer         1
Number           1
Service          1
Possible         1
Decision         1
List             1
Some             1
Such             1
Feeling          1
Pay              1
Town             1
The              1
Believe          1
Job              1
Force            1
Be               1
Body             1
Ready            1
Most             1
Eat              1
Night            1
Why              1
Detail           1
Name: count, dtype: int64
--Least_Product--
Detail
--Revanue--
147872.94999999998
4
--Repeated--
customer_id
C0500    1
C0062    1
C0205    1
C0039    1
C0244    1
C0112    1
C0094    1
C0256    1
C0121    1
C0447    1
C0118    1
C0429    1
C0080    1
C0315    1
C0275    1
C0491    1
C0191    1
C0253    1
C0252    1
C0144    1
C0385    1
C0028    1
C0245    1
C0258    1
C0441    1
C0235    1
C0128    1
C0490    1
C0142    1
C0287    1
C0181    1
C0208    1
C0266    1
C0471    1
C0146    1
C0469    1
C0178    1
C0311    1
C0477    1
C0003    1
C0209    1
C0151    1
C0410    1
C0412    1
C0449    1
C0129    1
C0495    1
C0248    1
C0388    1
C0349    1
C0442    1
C0060    1
C0196    1
C0347    1
C0236    1
Name: count, dtype: int64
--Top_Product--
product_name
Add              3
Many             3
Behind           3
Detail           2
Everything       2
Least            2
Program          2
Organization     2
Art              1
Store            1
Body             1
Same             1
Service          1
North            1
Senior           1
Stage            1
Keep             1
Night            1
Part             1
Market           1
Country          1
Compare          1
Trip             1
Around           1
West             1
Perform          1
List             1
Edge             1
Amount           1
Section          1
Why              1
Some             1
News             1
General          1
Environmental    1
Evening          1
Able             1
Such             1
Prepare          1
Value            1
Town             1
So               1
Network          1
Mind             1
Name: count, dtype: int64
--Least_Product--
Mind
--Revanue--
99819.55999999998
5
--Repeated--
customer_id
C0324    2
C0075    1
C0108    1
C0161    1
C0364    1
C0331    1
C0455    1
C0383    1
C0495    1
C0086    1
C0065    1
C0339    1
C0053    1
C0208    1
C0480    1
C0028    1
C0269    1
C0054    1
C0080    1
C0159    1
C0378    1
C0321    1
C0270    1
C0018    1
C0083    1
C0328    1
C0243    1
C0231    1
C0216    1
C0458    1
C0274    1
C0403    1
C0129    1
C0025    1
C0354    1
C0111    1
C0430    1
C0134    1
C0315    1
C0287    1
C0177    1
C0063    1
C0102    1
C0333    1
C0090    1
C0182    1
C0250    1
C0456    1
C0441    1
Name: count, dtype: int64
--Top_Product--
product_name
Change        2
Detail        2
Phone         2
Part          2
Store         2
The           2
Senior        2
Find          2
Everything    2
Tax           2
Program       1
Night         1
Amount        1
Job           1
Drive         1
North         1
First         1
Stage         1
Evening       1
Decision      1
Many          1
Ask           1
Happen        1
On            1
Feeling       1
Behind        1
Able          1
Dream         1
Least         1
Pay           1
Add           1
Compare       1
Number        1
Standard      1
Service       1
Art           1
Table         1
Why           1
Likely        1
Really        1
Name: count, dtype: int64
--Least_Product--
Really
--Revanue--
74185.19
6
--Repeated--
customer_id
C0191    2
C0327    2
C0063    2
C0047    2
C0497    2
        ..
C0382    1
C0185    1
C0499    1
C0135    1
C0057    1
Name: count, Length: 72, dtype: int64
--Top_Product--
product_name
First         3
Manage        3
Network       3
Prepare       3
So            3
Town          2
Value         2
Government    2
Senior        2
Same          2
North         2
Find          2
On            2
Country       2
Management    2
Keep          2
Light         2
General       2
Phone         1
Ready         1
Art           1
Trip          1
Decision      1
Around        1
Store         1
Table         1
Job           1
Compare       1
Standard      1
Why           1
Second        1
Number        1
West          1
Many          1
Market        1
Finish        1
Most          1
Mind          1
Eat           1
Dream         1
Pay           1
Black         1
Yes           1
Happen        1
Least         1
Work          1
Some          1
Program       1
Edge          1
Operation     1
The           1
Bed           1
Strategy      1
While         1
Tax           1
Drive         1
Name: count, dtype: int64
--Least_Product--
Drive
--Revanue--
125984.33
7
--Repeated--
customer_id
C0292    2
C0393    2
C0428    1
C0375    1
C0285    1
C0080    1
C0236    1
C0071    1
C0456    1
C0120    1
C0048    1
C0371    1
C0089    1
C0420    1
C0329    1
C0472    1
C0041    1
C0396    1
C0179    1
C0477    1
C0383    1
C0476    1
C0028    1
C0022    1
C0290    1
C0258    1
C0079    1
C0498    1
C0471    1
C0439    1
C0484    1
C0154    1
C0050    1
C0273    1
C0099    1
C0286    1
C0213    1
C0184    1
C0360    1
C0453    1
C0406    1
C0206    1
C0337    1
C0308    1
C0463    1
C0167    1
C0392    1
C0423    1
C0312    1
C0280    1
C0185    1
C0492    1
C0372    1
C0306    1
C0070    1
C0295    1
Name: count, dtype: int64
--Top_Product--
product_name
Bed              3
Behind           3
Work             3
Add              3
Drive            3
Environmental    2
Service          2
West             2
Job              2
Same             2
Some             2
Find             1
Around           1
Many             1
The              1
Light            1
Perform          1
Least            1
Everything       1
Value            1
So               1
While            1
Mind             1
Pay              1
Table            1
Part             1
Believe          1
Number           1
Protect          1
Eat              1
Why              1
Consumer         1
On               1
Art              1
Night            1
Yes              1
Edge             1
Body             1
Change           1
Market           1
Operation        1
Finish           1
Name: count, dtype: int64
--Least_Product--
Finish
--Revanue--
96078.60999999999
8
--Repeated--
customer_id
C0466    3
C0157    2
C0336    2
C0421    1
C0447    1
C0202    1
C0010    1
C0182    1
C0121    1
C0416    1
C0450    1
C0484    1
C0116    1
C0460    1
C0045    1
C0267    1
C0079    1
C0214    1
C0475    1
C0230    1
C0106    1
C0298    1
C0442    1
C0353    1
C0163    1
C0273    1
C0095    1
C0373    1
C0451    1
C0156    1
C0021    1
C0257    1
C0075    1
C0046    1
C0474    1
C0351    1
C0388    1
C0058    1
C0125    1
C0445    1
C0176    1
C0012    1
C0379    1
C0105    1
C0385    1
C0248    1
C0356    1
C0193    1
C0023    1
C0031    1
C0405    1
C0139    1
C0199    1
C0340    1
C0443    1
C0150    1
C0119    1
C0364    1
C0249    1
C0078    1
Name: count, dtype: int64
--Top_Product--
product_name
On               3
Country          3
Pay              2
Maybe            2
Change           2
Perform          2
Force            2
Store            2
Organization     2
North            2
Really           2
Phone            1
Light            1
According        1
Part             1
Body             1
Operation        1
Eat              1
Table            1
So               1
Where            1
Foot             1
Second           1
Manage           1
Why              1
Behind           1
Evening          1
Be               1
Environmental    1
Network          1
Compare          1
Finish           1
Consumer         1
Program          1
Value            1
Job              1
Prepare          1
Many             1
Some             1
The              1
Least            1
Service          1
Yes              1
Town             1
Drive            1
Government       1
Night            1
Ask              1
Coach            1
Most             1
Everything       1
Name: count, dtype: int64
--Least_Product--
Everything
--Revanue--
102602.68
9
--Repeated--
customer_id
C0452    2
C0394    2
C0047    2
C0148    1
C0325    1
C0269    1
C0373    1
C0487    1
C0282    1
C0290    1
C0084    1
C0215    1
C0374    1
C0061    1
C0129    1
C0002    1
C0007    1
C0438    1
C0414    1
C0112    1
C0233    1
C0041    1
C0004    1
C0143    1
C0420    1
C0095    1
C0368    1
C0316    1
C0444    1
C0199    1
C0219    1
C0312    1
C0369    1
C0314    1
C0305    1
C0329    1
C0267    1
C0234    1
C0266    1
C0377    1
C0098    1
C0460    1
C0204    1
C0237    1
C0151    1
C0354    1
C0238    1
C0058    1
C0481    1
C0070    1
C0166    1
C0092    1
C0335    1
Name: count, dtype: int64
--Top_Product--
product_name
Network         4
Likely          2
Coach           2
Prepare         2
Foot            2
Feeling         2
Keep            2
Possible        2
Tax             2
Organization    2
Change          1
Town            1
Really          1
Some            1
So              1
Table           1
Happen          1
Such            1
Stage           1
Amount          1
Be              1
Government      1
Most            1
Ahead           1
Art             1
Find            1
Standard        1
Strategy        1
List            1
Program         1
Behind          1
Service         1
Yes             1
Black           1
Bed             1
Dream           1
Ready           1
Why             1
Night           1
Perform         1
Part            1
Job             1
North           1
Compare         1
Name: count, dtype: int64
--Least_Product--
Compare
--Revanue--
95015.45999999999
10
--Repeated--
customer_id
C0473    2
C0410    2
C0100    2
C0357    1
C0305    1
C0237    1
C0428    1
C0290    1
C0285    1
C0107    1
C0497    1
C0431    1
C0193    1
C0432    1
C0311    1
C0362    1
C0080    1
C0140    1
C0255    1
C0232    1
C0269    1
C0058    1
C0399    1
C0228    1
C0079    1
C0159    1
C0074    1
C0421    1
C0457    1
C0331    1
C0030    1
C0470    1
C0374    1
C0045    1
C0479    1
C0219    1
C0133    1
C0320    1
C0315    1
C0267    1
C0253    1
C0120    1
C0013    1
C0378    1
C0213    1
C0171    1
C0413    1
C0006    1
C0354    1
C0405    1
C0154    1
C0166    1
C0059    1
C0175    1
C0316    1
C0106    1
Name: count, dtype: int64
--Top_Product--
product_name
Change           3
Program          3
Be               3
Ahead            2
Stage            2
Why              2
Evening          2
So               2
Environmental    2
West             2
Prepare          2
Possible         2
North            2
Bed              2
Around           2
Foot             2
Eat              1
Strategy         1
Operation        1
Tax              1
Consumer         1
Light            1
Add              1
General          1
Behind           1
Trip             1
Maybe            1
Body             1
Force            1
Part             1
Yes              1
Manage           1
Store            1
Compare          1
Management       1
Night            1
Second           1
Market           1
Where            1
Everything       1
Name: count, dtype: int64
--Least_Product--
Everything
--Revanue--
78645.33
11
--Repeated--
customer_id
C0167    2
C0244    2
C0404    2
C0417    2
C0055    1
        ..
C0125    1
C0212    1
C0237    1
C0406    1
C0197    1
Name: count, Length: 75, dtype: int64
--Top_Product--
product_name
While         4
Network       3
Ready         3
Phone         3
Operation     2
Yes           2
Maybe         2
Some          2
Town          2
Table         2
Edge          2
Detail        2
According     2
Eat           2
List          2
Coach         2
Same          2
Perform       2
Around        2
North         2
Happen        2
Dream         2
Management    1
Prepare       1
Behind        1
Body          1
Such          1
Consumer      1
Amount        1
Finish        1
Store         1
Change        1
Really        1
Foot          1
Follow        1
Least         1
Feeling       1
On            1
Work          1
So            1
Government    1
Away          1
Value         1
Program       1
Ask           1
Standard      1
Bed           1
Find          1
Evening       1
Strategy      1
Add           1
Number        1
Name: count, dtype: int64
--Least_Product--
Number
--Revanue--
133063.62
12
--Repeated--
customer_id
C0376    2
C0086    2
C0274    1
C0237    1
C0120    1
C0243    1
C0272    1
C0148    1
C0348    1
C0350    1
C0470    1
C0490    1
C0471    1
C0172    1
C0411    1
C0336    1
C0395    1
C0244    1
C0173    1
C0161    1
C0345    1
C0007    1
C0269    1
C0180    1
C0129    1
C0013    1
C0030    1
C0487    1
C0363    1
C0383    1
C0028    1
C0387    1
C0241    1
C0464    1
C0181    1
C0384    1
C0134    1
C0297    1
C0027    1
C0415    1
C0014    1
C0043    1
C0040    1
C0068    1
C0141    1
C0380    1
C0090    1
C0338    1
C0414    1
C0401    1
C0249    1
C0442    1
C0044    1
C0479    1
C0386    1
C0122    1
C0372    1
C0108    1
C0439    1
Name: count, dtype: int64
--Top_Product--
product_name
Strategy        2
General         2
Government      2
While           2
Protect         2
Bed             2
Be              2
Job             2
Really          2
Body            2
First           1
Pay             1
Everything      1
Prepare         1
Keep            1
Many            1
Behind          1
So              1
Drive           1
Some            1
Away            1
Same            1
Least           1
Yes             1
Believe         1
Organization    1
Mind            1
Town            1
West            1
Management      1
Ready           1
Stage           1
Force           1
Black           1
Table           1
Tax             1
Program         1
Store           1
Happen          1
News            1
Dream           1
The             1
Amount          1
Seem            1
Perform         1
Night           1
Feeling         1
Light           1
Network         1
Add             1
Where           1
Name: count, dtype: int64
--Least_Product--
Where
--Revanue--
98196.36
2023
1
--Repeated--
customer_id
C0284    2
C0335    2
C0125    2
C0464    2
C0377    2
        ..
C0174    1
C0404    1
C0208    1
C0414    1
C0286    1
Name: count, Length: 68, dtype: int64
--Top_Product--
product_name
General         3
Seem            3
Mind            3
Perform         2
Value           2
Number          2
Operation       2
Table           2
Prepare         2
Section         2
Amount          2
North           2
Some            2
Protect         2
West            2
Work            1
Manage          1
Maybe           1
Government      1
Yes             1
Dream           1
Detail          1
The             1
Away            1
Drive           1
Everything      1
Stage           1
Store           1
So              1
Happen          1
Job             1
Coach           1
Follow          1
Tax             1
Body            1
Organization    1
Change          1
Light           1
Part            1
Such            1
While           1
Believe         1
Second          1
Around          1
Bed             1
Network         1
Feeling         1
Keep            1
Senior          1
Country         1
Why             1
Pay             1
Likely          1
Program         1
Able            1
Eat             1
Name: count, dtype: int64
--Least_Product--
Eat
--Revanue--
108926.39
2
--Repeated--
customer_id
C0297    1
C0468    1
C0241    1
C0018    1
C0202    1
C0232    1
C0043    1
C0355    1
C0487    1
C0184    1
C0332    1
C0246    1
C0083    1
C0440    1
C0013    1
C0396    1
C0095    1
C0361    1
C0441    1
C0198    1
C0272    1
C0219    1
C0358    1
C0295    1
C0318    1
C0264    1
C0455    1
C0214    1
C0114    1
C0102    1
C0168    1
C0118    1
C0167    1
C0122    1
C0446    1
C0457    1
C0242    1
C0028    1
C0111    1
C0092    1
C0070    1
C0324    1
C0104    1
C0017    1
C0031    1
C0057    1
C0215    1
C0113    1
C0081    1
C0464    1
C0497    1
C0045    1
C0251    1
C0243    1
C0008    1
C0377    1
C0197    1
Name: count, dtype: int64
--Top_Product--
product_name
North         4
Force         2
Tax           2
Black         2
Value         2
West          2
Network       2
Dream         2
While         2
Work          2
Program       2
Add           2
Management    2
Foot          1
Edge          1
Maybe         1
Section       1
Find          1
Consumer      1
Likely        1
Change        1
Protect       1
Away          1
Ahead         1
Body          1
Finish        1
Phone         1
Be            1
According     1
Keep          1
Amount        1
Most          1
Service       1
Same          1
News          1
Around        1
Operation     1
Some          1
Believe       1
Ask           1
Everything    1
Standard      1
Name: count, dtype: int64
--Least_Product--
Standard
--Revanue--
100614.26999999999
3
--Repeated--
customer_id
C0448    2
C0374    2
C0190    2
C0500    2
C0156    2
        ..
C0341    1
C0288    1
C0065    1
C0022    1
C0192    1
Name: count, Length: 84, dtype: int64
--Top_Product--
product_name
Follow           4
Foot             4
Art              3
Table            3
Feeling          3
Stage            3
Bed              3
Store            2
Such             2
Likely           2
Mind             2
On               2
Behind           2
Manage           2
Night            2
Town             2
Where            2
Consumer         2
Many             2
Some             2
Same             2
Amount           2
Seem             2
Value            2
Be               1
Pay              1
So               1